apiVersion: apps/v1
kind: Deployment
metadata:
  name: veacheslav-deployment
  namespace: veacheslav
spec:
  replicas: 1
  selector:
    matchLabels:
      app: veacheslav
  template:
    metadata:
      labels:
        app: veacheslav
    spec:
      initContainers:
      - name: init-nginx
        image: busybox
        command: [ 'sh', '-c', 'cp /config/default.conf /etc/nginx/conf.d/default.conf' ]
        volumeMounts:
        - name: nginx-config-volume
          mountPath: /config
        - name: nginx-conf
          mountPath: /etc/nginx/conf.d
      containers:
      - name: nginx
        image: nginx:latest
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 20
        env:
        - name: XMCYBER
          valueFrom:
            secretKeyRef:
              name: veacheslav-secret
              key: XMCYBER
        volumeMounts:
        - name: ssl-certs
          mountPath: "/etc/nginx/ssl"
          readOnly: true
        - name: nginx-conf
          mountPath: /etc/nginx/conf.d
      volumes:
      - name: ssl-certs
        secret:
          secretName: veacheslav-ssl
      - name: nginx-config-volume
        configMap:
          name: nginx-config
      - name: nginx-conf
        emptyDir: {}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: veacheslav
data:
  default.conf: |
    server {
    listen 80;
    server_name veacheslav;

    location / {
        default_type text/html;
        return 200 '
        <!DOCTYPE html>
        <html>
        <head>
            <title>Demo Page</title>
        </head>
        <body>
            <h1>Welcome to the demo page</h1>
            <p>The test was successfully completed.</p>
        </body>
        </html>';
    }
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: veacheslav-hpa
  namespace: veacheslav
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: veacheslav-deployment
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 70
